services:

  database:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: PetopiaDatabase
    ports:
      - "1433:1433"
    env_file:
      - ".env"
    environment:
      ACCEPT_EULA: ${MSSQL_ACCEPT_EULA}
      MSSQL_SA_PASSWORD: ${MSSQL_PASSWORD}

  cache:
    image: redis
    container_name: PetopiaCache
    ports:
      - "6379:6379"
    env_file:
      - ".env"
    command: --requirepass "${REDIS_PASSWORD}"

  storage:
    image: minio/minio
    container_name: PetopiaStorage
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ".env"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
