services:

  database:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: PetopiaDatabase
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "6LcjKUnAAAAAALUCYB2ZWI4DcCYnNFBzeN6G5L"

  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: PetotpiaStorage
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  cache:
    image: redis
    container_name: PetopiaCache
    ports:
      - "6379:6379"
    command: --requirepass "6LcjKUnAAAasdfFSDFYB2ZWI4DcCYnNFBzeN6G5L"
