services:

  database:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: PetopiaDatabase
    ports:
      - "1433:1433"
    env_file:
      - ".env"
    environment:
      ACCEPT_EULA: ${MSSQL_ACCEPT_EULA}
      MSSQL_SA_PASSWORD: ${MSSQL_PASSWORD}

  cache:
    image: redis
    container_name: PetopiaCache
    ports:
      - "6379:6379"
    env_file:
      - ".env"
    command: --requirepass "${REDIS_PASSWORD}"
