services:

  database:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: PetopiaDatabase
    ports:
      - "1433:1433"
    env_file:
      - ".env"
    environment:
      ACCEPT_EULA: ${MSSQL_ACCEPT_EULA}
      MSSQL_SA_PASSWORD: ${MSSQL_PASSWORD}

  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: PetopiaStorage
    ports:
      - "10000:10000"
    env_file:
      - ".env"
    environment:
      AZURITE_ACCOUNTS: "${AZURITE_USERNAME}:${AZURITE_PASSWORD}"

  cache:
    image: redis
    container_name: PetopiaCache
    ports:
      - "6379:6379"
    env_file:
      - ".env"
    command: --requirepass "${REDIS_PASSWORD}"

  searchEngine:
    image: elasticsearch:8.8.1
    container_name: PetopiaSearchEngine
    ports:
      - "9200:9200"
    env_file:
      - ".env"
    environment:
      xpack.security.enabled: ${ELASTIC_SECURITY_ENABLED}
      discovery.type: ${ELASTIC_DISCOVERY_TYPE}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
